input {
  file {
    path => "/var/log/suricata/eve.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    tags => ["suricata"]
  }
}

filter {
  if "_jsonparsefailure" in [tags] {
    drop {}
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
    remove_field => ["timestamp"]
  }

  if [alert][signature] {
    if [alert][signature] =~ /BLOQUEADO/ {
      mutate { add_tag => ["blocked", "ips_action"] }
    } else if [alert][signature] =~ /detectado/ {
      mutate { add_tag => ["detected", "ids_alert"] }
    }

    if [alert][signature] =~ /SQLi|SQL/ {
      mutate { add_field => { "attack_category" => "SQL Injection" } }
    } else if [alert][signature] =~ /XSS/ {
      mutate { add_field => { "attack_category" => "Cross-Site Scripting" } }
    } else if [alert][signature] =~ /LFI|Path/ {
      mutate { add_field => { "attack_category" => "Path Traversal" } }
    } else if [alert][signature] =~ /SCAN/ {
      mutate { add_field => { "attack_category" => "Network Scan" } }
    } else if [alert][signature] =~ /TOOL/ {
      mutate { add_field => { "attack_category" => "Attack Tool" } }
    } else if [alert][signature] =~ /CMDi|CMD/ {
      mutate { add_field => { "attack_category" => "Command Injection" } }
    } else if [alert][signature] =~ /BRUTE/ {
      mutate { add_field => { "attack_category" => "Brute Force" } }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "suricata-%{+YYYY.MM.dd}"
  }
}
