input {
  file {
    path => "/var/log/suricata/eve.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
  
  if [alert][signature] =~ /BLOQUEADO/ {
    mutate {
      add_tag => ["blocked", "ips_action"]
    }
  }
  
  if [alert][signature] =~ /detectado/ {
    mutate {
      add_tag => ["detected", "ids_alert"]
    }
  }
  
  if [alert][signature] =~ /SQLi|SQL/ {
    mutate { add_field => { "attack_category" => "SQL Injection" } }
  } else if [alert][signature] =~ /XSS/ {
    mutate { add_field => { "attack_category" => "Cross-Site Scripting" } }
  } else if [alert][signature] =~ /LFI|Path/ {
    mutate { add_field => { "attack_category" => "Path Traversal" } }
  } else if [alert][signature] =~ /SCAN/ {
    mutate { add_field => { "attack_category" => "Network Scan" } }
  } else if [alert][signature] =~ /TOOL/ {
    mutate { add_field => { "attack_category" => "Attack Tool" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "suricata-%{+YYYY.MM.dd}"
  }
  
}
